### ISSUE TITLE
Should people be able to upvote their own comments?

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#173]
Like on reddit. We can have it so it auto-votes up.

**Comment by Gofven** [comment]
Done, see if it works c:

**Comment by Kattenelvis** [comment]
Doesn't seem to work, I still get the error message "Can't vote on a comment that belongs to yourself"

**Comment by Gofven** [comment]
Updated it, see if it works now c:
